create table businesses (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    slug varchar(255),
    payment_instructions varchar(1000),
    contact_phone varchar(255),
    logo_path varchar(255),
    constraint uk_businesses_slug unique (slug)
);

create table users (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    name varchar(255) not null,
    phone varchar(255) not null,
    pin_hash varchar(255) not null,
    role varchar(255) not null,
    active boolean not null,
    tier integer not null,
    company_name varchar(255),
    address varchar(255),
    constraint fk_users_business foreign key (business_id) references businesses (id),
    constraint uk_users_business_phone unique (business_id, phone)
);

create table categories (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    name varchar(255),
    constraint fk_categories_business foreign key (business_id) references businesses (id),
    constraint uk_categories_business_name unique (business_id, name)
);

create table size_options (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    label varchar(255) not null,
    constraint fk_size_options_business foreign key (business_id) references businesses (id),
    constraint uk_size_options_business_label unique (business_id, label)
);

create table size_set_templates (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    name varchar(255) not null,
    size_labels varchar(255) not null,
    constraint fk_size_set_templates_business foreign key (business_id) references businesses (id),
    constraint uk_size_set_templates_business_name unique (business_id, name)
);

create table products (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    category_id bigint,
    product_code varchar(255),
    name varchar(255) not null,
    description varchar(2000),
    price numeric(38, 2) not null,
    minimum_tier_required integer not null,
    active boolean not null,
    created_at timestamp,
    constraint fk_products_business foreign key (business_id) references businesses (id),
    constraint fk_products_category foreign key (category_id) references categories (id),
    constraint uk_products_business_product_code unique (business_id, product_code)
);

create table product_colors (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    name varchar(255),
    image_path varchar(255),
    active boolean not null,
    constraint fk_product_colors_product foreign key (product_id) references products (id)
);

create table inventory_stock (
    id bigint generated by default as identity primary key,
    product_color_id bigint not null,
    size_label varchar(255) not null,
    quantity integer not null,
    constraint fk_inventory_stock_product_color foreign key (product_color_id) references product_colors (id),
    constraint uk_inventory_stock_color_size unique (product_color_id, size_label)
);

create table size_sets (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    name varchar(255) not null,
    size_labels varchar(255) not null,
    template_id bigint,
    constraint fk_size_sets_product foreign key (product_id) references products (id)
);

create table customer_orders (
    id bigint generated by default as identity primary key,
    business_id bigint not null,
    customer_id bigint not null,
    status varchar(255) not null,
    total_amount numeric(38, 2) not null,
    created_at timestamp not null,
    approved_at timestamp,
    payment_submitted_at timestamp,
    confirmed_at timestamp,
    transaction_id varchar(255),
    payment_proof_path varchar(255),
    out_of_stock_summary varchar(3000),
    constraint fk_customer_orders_business foreign key (business_id) references businesses (id),
    constraint fk_customer_orders_customer foreign key (customer_id) references users (id)
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_color_id bigint,
    size_set_id bigint,
    product_code varchar(255),
    product_name varchar(255),
    color_name varchar(255),
    size_set_name varchar(255),
    size_labels varchar(255),
    quantity integer not null,
    price_each numeric(38, 2) not null,
    out_of_stock boolean not null,
    out_of_stock_reason varchar(1000),
    constraint fk_order_items_order foreign key (order_id) references customer_orders (id)
);

create table stored_files (
    id varchar(255) primary key,
    business_id bigint not null,
    folder varchar(255) not null,
    filename varchar(255) not null,
    content_type varchar(255) not null,
    data bytea not null,
    created_at timestamp
);

create index idx_users_business_role on users (business_id, role);
create index idx_products_business_created on products (business_id, created_at desc, id desc);
create index idx_products_catalog on products (business_id, active, minimum_tier_required, created_at desc);
create index idx_product_colors_product on product_colors (product_id);
create index idx_inventory_stock_color on inventory_stock (product_color_id);
create index idx_size_sets_product on size_sets (product_id);
create index idx_customer_orders_business_created on customer_orders (business_id, created_at desc);
create index idx_customer_orders_business_status on customer_orders (business_id, status);
create index idx_customer_orders_customer_created on customer_orders (customer_id, created_at desc);
create index idx_order_items_order on order_items (order_id);
create index idx_order_items_product_color on order_items (product_color_id);
create index idx_stored_files_business_folder on stored_files (business_id, folder);
